# Generated by Django 6.0.7 on 2026-07-16 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageThread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="portal.messagethread",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Process",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("reference_code", models.CharField(max_length=64, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "workos_organization_id",
                    models.CharField(
                        blank=True,
                        help_text="WorkOS org ID for RBAC / Vault scoping (placeholder).",
                        max_length=255,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        help_text="Internal process manager (placeholder until WorkOS ↔ User sync).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_processes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "processes",
            },
        ),
        migrations.CreateModel(
            name="ParcelPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parcel_label", models.CharField(blank=True, max_length=128)),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("storage_key", models.CharField(max_length=512)),
                ("captured_at", models.DateTimeField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="portal.process",
                    ),
                ),
            ],
            options={
                "ordering": ["captured_at"],
            },
        ),
        migrations.AddField(
            model_name="messagethread",
            name="process",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="message_threads",
                to="portal.process",
            ),
        ),
        migrations.CreateModel(
            name="Intervention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "intervention_type",
                    models.CharField(
                        choices=[
                            ("thinning", "Thinning"),
                            ("planting", "Planting"),
                            ("pruning", "Pruning"),
                            ("survey", "Survey"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("performed_at", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interventions",
                        to="portal.process",
                    ),
                ),
            ],
            options={
                "ordering": ["-performed_at"],
            },
        ),
        migrations.CreateModel(
            name="AccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("workos_user_id", models.CharField(blank=True, max_length=255)),
                ("resource_type", models.CharField(max_length=64)),
                ("resource_id", models.CharField(blank=True, max_length=64)),
                ("action", models.CharField(max_length=32)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("accessed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "process",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="portal.process",
                    ),
                ),
            ],
            options={
                "ordering": ["-accessed_at"],
            },
        ),
        migrations.CreateModel(
            name="ProcessDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("contract", "Contract"),
                            ("forest_plan", "Forest management plan"),
                            ("annual_report", "Annual report"),
                            ("invoice", "Invoice"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "storage_key",
                    models.CharField(
                        help_text="Private object storage key (S3/R2/MinIO).",
                        max_length=512,
                    ),
                ),
                ("file_size_bytes", models.PositiveBigIntegerField(default=0)),
                ("published_at", models.DateTimeField(auto_now_add=True)),
                (
                    "process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="portal.process",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="ProcessMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner (senhorio)"),
                            ("co_owner", "Co-owner"),
                            ("heir", "Heir"),
                            ("accountant", "Accountant"),
                            ("manager", "Process manager (internal)"),
                        ],
                        max_length=32,
                    ),
                ),
                ("workos_user_id", models.CharField(blank=True, max_length=255)),
                ("notify_by_email", models.BooleanField(default=True)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="portal.process",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="process_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("process", "user")},
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notify_new_documents", models.BooleanField(default=True)),
                ("notify_new_messages", models.BooleanField(default=True)),
                ("notify_upcoming_operations", models.BooleanField(default=True)),
                (
                    "membership",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preference",
                        to="portal.processmembership",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScheduledOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("scheduled_start", models.DateField()),
                ("scheduled_end", models.DateField(blank=True, null=True)),
                ("location_notes", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_operations",
                        to="portal.process",
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_start"],
            },
        ),
    ]
