# Generated by Django 6.0.7 on 2026-07-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="process",
            name="area_hectares",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="process",
            name="location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="process",
            name="progress_percent",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="process",
            name="status",
            field=models.CharField(
                choices=[
                    ("planning", "Em planeamento"),
                    ("active", "Em curso"),
                    ("monitoring", "Em acompanhamento"),
                    ("completed", "Concluído"),
                ],
                default="active",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="scheduledoperation",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "Planeada"),
                    ("confirmed", "Confirmada"),
                    ("completed", "Concluída"),
                    ("postponed", "Adiada"),
                ],
                default="planned",
                max_length=32,
            ),
        ),
    ]
