# Generated by Django 6.0.7 on 2026-07-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_process_area_hectares_process_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='intervention_type',
            field=models.CharField(choices=[('thinning', 'Desbaste'), ('planting', 'Plantação'), ('pruning', 'Poda'), ('survey', 'Levantamento'), ('other', 'Outra')], max_length=32),
        ),
        migrations.AlterField(
            model_name='processdocument',
            name='document_type',
            field=models.CharField(choices=[('contract', 'Contrato'), ('forest_plan', 'Plano de gestão florestal'), ('annual_report', 'Balanço anual'), ('invoice', 'Faturação'), ('other', 'Outro')], max_length=32),
        ),
        migrations.AlterField(
            model_name='processmembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Senhorio'), ('co_owner', 'Co-proprietário'), ('heir', 'Herdeiro'), ('accountant', 'Contabilista'), ('manager', 'Gestor de processo (interno)')], max_length=32),
        ),
    ]
