# Generated by Django 6.0.7 on 2026-07-19 08:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_intervention_intervention_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Internal process manager.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_processes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='process',
            name='progress_percent',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='process',
            name='workos_organization_id',
            field=models.CharField(blank=True, help_text='Optional WorkOS organization id used for external RBAC scoping.', max_length=255),
        ),
    ]
