# Generated by Django 6.0.7 on 2026-07-19 08:18

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="approach_body",
            field=wagtail.fields.RichTextField(
                default="<p>Gerimos propriedades florestais com rigor técnico, proximidade e uma visão de longo prazo. Cada decisão é documentada e cada senhorio acompanha o seu processo com total clareza.</p>"
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="approach_title",
            field=models.CharField(
                default="Uma relação de confiança, construída no terreno.",
                max_length=160,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="contact_email",
            field=models.EmailField(default="geral@antarr.pt", max_length=254),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_eyebrow",
            field=models.CharField(
                default="Gestão florestal com visão de futuro", max_length=120
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_intro",
            field=models.TextField(
                default="Gestão florestal próxima, transparente e responsável — da análise inicial ao acompanhamento de cada intervenção."
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_title",
            field=models.CharField(
                default="Cuidamos da sua terra. Valorizamos o seu futuro.",
                max_length=180,
            ),
        ),
    ]
